safe: true
auto: true
server: true
baseurl: /

source: .
destination: ./_site

title: "Those Green Mountains"
desc: "A tribute to the magestic peaks of Vermont."
longdesc: "Those Green Mountains is a designers tribute to the magestic peaks of Vermont, those of the Green Mountain range."